import sys
from time import sleep

import pygame

from settings import Settings
from ship import Ship
from bullet import Bullet
from alien import Alien
from game_stats import GameStats
from button import Button
from scoreboard import Scoreboard


class AlienInvasion:
    """A class designed to manage resources and game operations."""

    def __init__(self):
        """Initialization of the game and its resources."""
        pygame.init()
        self.settings = Settings()

        self.screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
        self.settings.screen_width = self.screen.get_rect().width
        self.settings.screen_height = self.screen.get_rect().height
        pygame.display.set_caption("Alien invasion")

        # creating an instance storing statistical data about the game
        self.stats = GameStats(self)
        # creating an instance of the Scoreboard class
        self.sb = Scoreboard(self)

        self.ship = Ship(self)
        self.bullets = pygame.sprite.Group()
        self.aliens = pygame.sprite.Group()

        self._create_fleet()

        # creating a Play button
        self.play_button = Button(self, "Play")

    def run_game(self):
        """Starting the main game loop."""
        while True:
            self._check_events()

            if self.stats.game_active:
                self.ship.update()
                self._update_bullets()
                self._update_aliens()

            self._update_screen()

    def _check_events(self):
        """Response to events generated by keyboard and mouse."""
        # waiting for a key or mouse button to be pressed
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                self._check_keydown_events(event)
            elif event.type == pygame.KEYUP:
                self._check_keyup_events(event)
            elif event.type == pygame.MOUSEBUTTONDOWN:
                mouse_pos = pygame.mouse.get_pos()
                self._check_play_button(mouse_pos)

    def _check_keydown_events(self, event):
        """Reaction to keystroke."""
        if event.key == pygame.K_RIGHT:
            self.ship.moving_right = True
        elif event.key == pygame.K_LEFT:
            self.ship.moving_left = True
        elif event.key == pygame.K_q:
            sys.exit()
        elif event.key == pygame.K_SPACE:
            self._fire_bullet()

    def _check_keyup_events(self, event):
        """Reaction to key release."""
        if event.key == pygame.K_RIGHT:
            self.ship.moving_right = False
        elif event.key == pygame.K_LEFT:
            self.ship.moving_left = False

    def _check_play_button(self, mouse_pos):
        """Starting a new game when the user clicks the Play button."""
        button_clicked = self.play_button.rect.collidepoint(mouse_pos)
        if button_clicked and not self.stats.game_active:
            # resetting game dynamic settings
            self.settings.initialize_dynamic_settings()

            # resetting game statistics
            self.stats.reset_stats()
            self.stats.game_active = True
            self.sb.prep_score()
            self.sb.prep_level()

            # deleting the content of the groups aliens and bullets
            self.aliens.empty()
            self.bullets.empty()

            # creating new fleet and centering the ship
            self._create_fleet()
            self.ship.center_ship()

            # hide mouse cursor
            pygame.mouse.set_visible(False)

    def _fire_bullet(self):
        """Creating a new bullet and adding it to the bullets group."""
        if len(self.bullets) < self.settings.bullets_allowed:
            new_bullet = Bullet(self)
            self.bullets.add(new_bullet)

    def _update_bullets(self):
        """Updating the position of the bullets and removing bullets
        that are off-screen."""
        # updating the position of the bullets
        self.bullets.update()

        # removing bullets that are off-screen
        for bullet in self.bullets.copy():
            if bullet.rect.bottom <= 0:
                self.bullets.remove(bullet)

        self._check_bullet_alien_collisions()

    def _check_bullet_alien_collisions(self):
        """Reaction to a collision between a bullet and an alien."""
        # checking if any of the bullets hit the alien.
        # if so, we remove both the bullet and the alien
        collisions = pygame.sprite.groupcollide(
            self.bullets, self.aliens, True, True)

        if collisions:
            for aliens in collisions.values():
                self.stats.score += self.settings.alien_points * len(aliens)
            self.sb.prep_score()
            self.sb.check_high_score()

        if not self.aliens:
            # getting rid of existing bullets and creating a new fleet
            self.bullets.empty()
            self.settings.increase_speed()
            self._create_fleet()

            # increment level number
            self.stats.level += 1
            self.sb.prep_level()

    def _update_aliens(self):
        """Checking if the alien fleet is at the edge of the screen and
        updating the location of all aliens in the fleet."""
        self._check_fleet_edges()
        self.aliens.update()

        # alien-ship collision detection
        if pygame.sprite.spritecollideany(self.ship, self.aliens):
            self._ship_hit()

        # searching for aliens reaching the bottom of the screen
        self._check_aliens_bottom()

    def _ship_hit(self):
        """Reaction to alien hitting ship."""
        if self.stats.ships_left > 0:
            # decreasing the value stored in ships_left
            self.stats.ships_left -= 1

            # deleting the content of the groups aliens and bullets
            self.aliens.empty()
            self.bullets.empty()

            # creating new fleet and centering the ship
            self._create_fleet()
            self.ship.center_ship()

            # pause
            sleep(0.5)
        else:
            self.stats.game_active = False
            # mouse cursor visible again
            pygame.mouse.set_visible(True)

    def _check_aliens_bottom(self):
        """Checking if any aliens have reached the bottom of the screen."""
        screen_rect = self.screen.get_rect()
        for alien in self.aliens.sprites():
            if alien.rect.bottom >= screen_rect.bottom:
                # just like when a ship collides with an alien
                self._ship_hit()
                break

    def _create_fleet(self):
        """Creation of a complete alien fleet."""
        # creation of an alien and determining how many aliens will fit in a row
        # the distance between each alien is equal to the width of the alien
        alien = Alien(self)
        alien_width, alien_height = alien.rect.size
        available_space_x = self.settings.screen_width - (2 * alien_width)
        number_aliens_x = available_space_x // (2 * alien_width)

        # determining how many rows of aliens will fit on the screen
        ship_height = self.ship.rect.height
        available_space_y = (self.settings.screen_height -
                             (3 * alien_height) - ship_height)
        number_rows = available_space_y // (2 * alien_height)

        # creating a full alien fleet
        for row_number in range(number_rows):
            for alien_number in range(number_aliens_x):
                self._create_alien(alien_number, row_number)

    def _create_alien(self, alien_number, row_number):
        """Creating an alien and placing it in a row."""
        alien = Alien(self)
        alien_width, alien_height = alien.rect.size
        alien.x = alien_width + 2 * alien_width * alien_number
        alien.rect.x = alien.x
        alien.rect.y = alien.rect.height + 2 * alien.rect.height * row_number
        self.aliens.add(alien)

    def _check_fleet_edges(self):
        """Appropriate reaction when an alien reaches the edge of the
        screen."""
        for alien in self.aliens.sprites():
            if alien.check_edges():
                self._change_fleet_direction()
                break

    def _change_fleet_direction(self):
        """Shifting the entire fleet down and changing the direction in
        which it moves."""
        for alien in self.aliens.sprites():
            alien.rect.y += self.settings.fleet_drop_speed
        self.settings.fleet_direction *= -1

    def _update_screen(self):
        """Updating images on the screen and moving to a new screen."""
        # screen refreshing during each loop iteration
        self.screen.fill(self.settings.bg_color)
        self.ship.blitme()
        for bullet in self.bullets.sprites():
            bullet.draw_bullet()
        self.aliens.draw(self.screen)

        # displaying information about scoring
        self.sb.show_score()

        # displaying the button only when the game is inactive
        if not self.stats.game_active:
            self.play_button.draw_button()

        # displaying the last modified screen
        pygame.display.flip()


if __name__ == '__main__':
    # creating a game instance and running it
    ai = AlienInvasion()
    ai.run_game()
